Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: np-complete-doj.in
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
    DeletionPolicy: Retain
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: np-complete-doj.in
      SubjectAlternativeNames:
        - '*.np-complete-doj.in'
      DomainValidationOptions:
        DomainName: np-complete-doj.in
        HostedZoneId: Z1UV67RHS6GARQ
Outputs:
  NpCompleteWebsiteBucket:
    Value: !Ref WebsiteBucket
  NpCompleteWebsiteURL:
    Value: !GetAtt WebsiteBucket.WebsiteURL
